name: github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 15

    - name: Build with Maven
      run: mvn -B install --no-transfer-progress --file pom.xml
